### ISSUE TITLE
--persist=.

### ISSUE THREAD

**Issue by Summertime** [gjpin/itch-flatpak#2]
`--persist=.` in case of games that store their saves in $HOME subfolders other than .config

**Comment by lil5** [comment]
@Summertime You can also just add `--filesystem=home` via Flatseal.

**Comment by Summertime** [comment]
That'd give access to ssh keys, GPG keys, editing .bashrc la sandbox escape, etc

**Comment by gjpin** [comment]
Thanks @Summertime . Added!
